"use client";
import { FormEvent, useState } from "react";
export function InquiryForm(){
 const [sent,setSent]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); const fd=new FormData(e.currentTarget); if(fd.get("website")){return} if(!fd.get("name")||!fd.get("email")||!fd.get("service")||!fd.get("message")){setError("Vyplňte prosím všechna povinná pole.");return} setError("");setLoading(true);await new Promise(r=>setTimeout(r,700));setLoading(false);setSent(true)}
 if(sent)return <div className="success" role="status"><strong>Děkujeme, údaje byly zkontrolovány.</strong><p>Formulář je připravený, ale zatím není napojený na e-mailovou službu. Pro ostré odeslání prosím použijte telefon nebo e-mail.</p></div>;
 return <form className="form" onSubmit={submit} noValidate><div className="fieldGrid"><label>Jméno a firma *<input name="name" autoComplete="name" required/></label><label>E-mail *<input name="email" type="email" autoComplete="email" required/></label><label>Telefon<input name="phone" type="tel" autoComplete="tel"/></label><label>Typ služby *<select name="service" defaultValue="" required><option value="" disabled>Vyberte službu</option><option>Doprava</option><option>Skladování a logistika</option><option>Pneuservis</option><option>Jiné</option></select></label></div><label className="honeypot" aria-hidden="true">Web<input name="website" tabIndex={-1} autoComplete="off"/></label><label>Popis požadavku *<textarea name="message" rows={6} required placeholder="Trasa, typ a množství nákladu, termín nebo požadovaná servisní služba…"/></label><label className="consent"><input type="checkbox" required/> Souhlasím se zpracováním údajů za účelem vyřízení poptávky. *</label>{error&&<p className="formError" role="alert">{error}</p>}<button className="button" disabled={loading}>{loading?"Kontroluji…":"Odeslat poptávku"}</button><p className="formNote">Poznámka: formulář zatím neposílá e-mail. Údaje neopouštějí váš prohlížeč.</p></form>
}

